django/web/apps/marketing/urls.py
"""
Langolab -- learn foreign languages by speaking with random native speakers over webcam.
Copyright (C) 2011 Adam Duston

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

from django.conf.urls.defaults import *

urlpatterns = patterns(
    'marketing.views',
    url(r'^$', 'index', name='index'),
    url(r'^interest/$', 'interest', name='interest')
)

urlpatterns += patterns(
    '',
    url(r'^interaction/\d+/$', 'django.views.generic.simple.direct_to_template', 
        {'template':'marketing/interaction.html', 
         'extra_context': {'hide_nav':True}}),
    url(r'^interaction\-notes/\d+/$', 'django.views.generic.simple.direct_to_template', 
        {'template':'marketing/interaction-notes.html', 
         'extra_context': {'hide_nav':True}}),
    url(r'^dashboard/$', 'django.views.generic.simple.direct_to_template', 
        {'template':'marketing/dashboard.html', 
         'extra_context': {'hide_nav':True}}),
)

django/web/urls.py
"""
Langolab -- learn foreign languages by speaking with random native speakers over webcam.
Copyright (C) 2011 Adam Duston

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

from django.conf.urls.defaults import *
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^about/', 'django.views.generic.simple.direct_to_template', 
        {'template':'about.html'}, name="about"),
    url(r'^contact/', 'django.views.generic.simple.direct_to_template', 
        {'template':'contact.html'}, name="contact"),
    (r'^for_teachers/', include('marketing.urls', namespace="marketing")),
    (r'^llauth/', include('llauth.urls', namespace='llauth')),
    (r'^scheduling/', include('scheduling.urls', namespace='scheduling')),
    (r'^admin/', include(admin.site.urls)),
    (r'^jsdemo/(\w+)', 'jsdemo.views.jsdemo'),
    (r'^jstest/(\w+)', 'jstest.views.jstest'),
    (r'^socialauth/', include('socialauth.urls')),
    url(r'^logout/', 'django.contrib.auth.views.logout', name='logout'),
)

if settings.DEBUG:
    urlpatterns += patterns(
        '',
        (r'^site_media/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        (r'^favicon\.ico$', 'django.views.static.serve',
         {'document_root': settings.MEDIA_ROOT, 
          'path': 'images/favicon.ico', 
          'show_indexes': True}))

urlpatterns += patterns(
    '',
    (r'', include('conversations.urls', namespace='conversations')),)

django/web/apps/marketing/models.py
"""
Langolab -- learn foreign languages by speaking with random native speakers over webcam.
Copyright (C) 2011 Adam Duston

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

from django.db import models

class LLExchangeInterest(models.Model):
    name = models.CharField(max_length=255, blank=False)
    school = models.CharField(max_length=255, blank=True)
    position = models.CharField(max_length=255, blank=True)
    email = models.EmailField(blank=False)

django/web/apps/marketing/forms.py
"""
Langolab -- learn foreign languages by speaking with random native speakers over webcam.
Copyright (C) 2011 Adam Duston

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

from django.forms import ModelForm
from marketing.models import LLExchangeInterest
from django.core.mail import send_mail

class LLExchangeInterestForm(ModelForm):
    class Meta:
        model = LLExchangeInterest

    def send(self):
        text = "Interest from \n\n{0}\n\n{1}\n\n{2}\n\n{3}".format(
            self.cleaned_data['name'],
            self.cleaned_data['school'],
            self.cleaned_data['position'],
            self.cleaned_data['email'])
        send_mail('Langolab interest received',
                  text,
                  'noreply@langolab.com',
                  ['aduston@gmail.com'])

    def get_errors(self):
        from django.utils.encoding import force_unicode
        output = {}
        for key, value in self.errors.items():
            output[key] = '/n'.join([force_unicode(i) for i in value])
        return output

django/web/apps/marketing/views.py
"""
Langolab -- learn foreign languages by speaking with random native speakers over webcam.
Copyright (C) 2011 Adam Duston

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

from django.conf import settings
from django.template import RequestContext
from django.http import HttpResponse
from django.shortcuts import render_to_response
from marketing.forms import LLExchangeInterestForm
from django.utils import simplejson

def index(request):
    return render_to_response(
        'marketing/index.html',
        { 'form': LLExchangeInterestForm(),
          'fb_appid': settings.FACEBOOK_APP_ID},
        context_instance=RequestContext(request))

def interest(request):
    output = dict(success=False)
    form = LLExchangeInterestForm(request.POST)
    if form.is_valid():
        if not settings.DEBUG:
            form.send()
        form.save()
        output['success'] = True
    else:
        output['errors'] = form.get_errors()
    return HttpResponse(simplejson.dumps(output), 'text/javascript')

django/web/templates/marketing/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en" xmlns:fb="http://www.facebook.com/2008/fbml">
  <head>
    <title>Dual Immersion Platform - langoLAB</title>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
    <meta name="keywords" content=""/>
    <meta property="fb:page_id" content="51317678400" />
    <link rel="image_src" href="{{MEDIA_URL}}images/logo.jpg"/>
    <link rel="stylesheet" media="screen" type="text/css" href="{{MEDIA_URL}}css/ll.css"/>
    <link rel="shortcut icon" type="image/icon" href="/favicon.ico" />
    {% block css %}{% endblock %}
    <script charset="utf-8" type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.4.0/jquery.min.js"></script>
    {% block js %}{% endblock %}
  </head>
  <body>
    <div id="ll_nonFooter">
      <div id="ll_content">
        <div class="site-header">
          <div class="fixed-lg">
            <img class="logo" src="{{MEDIA_URL}}images/ll-logo-header.png"/>
            {% if not hide_nav %}
              <div class="mainNavTabCap">&nbsp;</div>
              <a class="mainNavTab" href="http://videolangolab.com">Langolab Videos</a>
            {% endif %}
          </div>
        </div>
        <div class="fixed-lg main-content">
          <table cellspacing="0" cellpadding="0" class="siteBox gwt-DecoratorPanel">
            <tr class="top"><td class="topLeft"><div class="corner topLeftInner"></div></td><td class="topCenter"><div class="topCenterInner"></div></td><td class="topRight"><div class="corner topRightInner"></div></td></tr>
            <tr class="middle"><td class="middleLeft"><div class="middleLeftInner"></div></td><td class="middleCenter">
                <div class="middleCenterInner">
                  {% block content %}{% endblock %}
                </div>
              </td><td class="middleRight"><div class="middleRightInner"></div></td></tr>
            <tr class="bottom"><td class="bottomLeft"><div class="corner bottomLeftInner"></div></td><td class="bottomCenter"><div class="bottomCenterInner"></div></td><td class="bottomRight"><div class="corner bottomRightInner"></div></td></tr>
          </table>
        </div>
      </div>
    </div>
    <div id="ll_footer" class="fixed-lg">
      <div class="footerTop">
        <div class="speechBubble clear">
          <div class="twitter" onclick="window.open('http://www.twitter.com/langolab', 'twitterLL');">&nbsp;</div>
          <div class="facebook" onclick="window.open('http://www.facebook.com/langoLAB', 'fbLL');">&nbsp;</div>
        </div>
        <div class="bird">
          <img src="{{MEDIA_URL}}images/bird-footer.png" />
        </div>
        <div id="ll_bottomLinks" class="clear">
          <span><a class="ll-FooterLink ll-LinkButton" href="/about">About</a></span>
          <span><a class="ll-FooterLink ll-LinkButton" href="http://blog.langolab.com">Blog</a></span>
          <span><a class="ll-FooterLink ll-LinkButton" href="/contact">Contact</a></span>
        </div>
        <div id="ll_copyright">
          <span>&copy; Copyright 2010 <b>LangoLAB, LLC</b> All Rights Reserved</span>
        </div>
      </div>
    </div>
  </body>
  <script type="text/javascript" charset="utf-8" src="http://www.google-analytics.com/ga.js"></script> 
  <script type="text/javascript" charset="utf-8">
    window.pageTracker = _gat._getTracker("UA-4038971-3");
    window.pageTracker._initData();
    window.pageTracker._trackPageview();
  </script> 
</html>

django/web/templates/marketing/dashboard.html
{% extends "marketing/base.html" %}
{% block css %}
<link rel="stylesheet" media="screen" type="text/css" href="{{MEDIA_URL}}css/dashboard.css"/>
{% endblock %}
{% block content %}
<h2>Session Record for Forrest Brown</h2>
<div class="clear">
  <img class="student-image" src="{{MEDIA_URL}}images/forrest.png"/>
  <div class="student-description">
    <strong>Student:</strong> Forrest Brown<br/>
    <strong>Student ID:</strong> 88-22-41<br/>
    <strong>Sessions Logged:</strong> 42<br/>
    <strong>Time Logged:</strong> 38:52:34
  </div>
</div>
<h2>Recent Sessions</h2>
<div class="session clear">
  <img class="session-image" src="{{MEDIA_URL}}images/jurgen.jpg"/>
  <div class="session-description">
    Jürgen Schiller<br/>
    October 15 at 8:42am<br/>
    42 minutes, 38 seconds
  </div>
  <div class="session-snippet">
    Ist es etwas, das man fahren kann?<br/>
    Es ist ein Auto?...<br/>
    <a class="ll-LinkButton" href="#">View full transcript</a>
  </div>
</div>
<div class="session clear">
  <img class="session-image" src="{{MEDIA_URL}}images/lola.jpg"/>
  <div class="session-description">
    Lola Müller<br/>
    October 14 at 8:36am<br/>
    49 minutes, 12 seconds
  </div>
  <div class="session-snippet">
    Ist es etwas, das man fahren kann?<br/>
    Es ist ein Auto?...<br/>
    <a class="ll-LinkButton" href="#">View full transcript</a>    
  </div>
</div>
<a class="ll-LinkButton" href="#">See earlier sessions...</a>
{% endblock %}

django/web/templates/marketing/index.html
{% extends "marketing/base.html" %}
{% load i18n %}
{% block js %}
<script type="text/javascript">
  var IMAGES_DIR = "{{MEDIA_URL}}images/";
</script>
<script type="text/javascript" src="{{MEDIA_URL}}js/jquery.nyroModal-1.6.2.min.js"></script>
<script type="text/javascript" src="{{MEDIA_URL}}js/jquery.cookie.js"></script>
<script type="text/javascript" src="{{MEDIA_URL}}js/jquery.form.js"></script>
<script type="text/javascript" src="{{MEDIA_URL}}js/pages/immersion-index.js"></script>
{% endblock %}
{% block content %}
<h1>The langoLAB Virtual Dual Immersion Platform</h1>
<div class="clear">
  <div id="leftCol">
    <h2>Is your school interested in adding a virtual immersion component to its language curriculum?</h2>
    <p>Langolab lets you introduce a virtual language exchange program into your department the easy way.</p>
    <p>With Langolab, students get paired with native speakers of the target language to converse and interact in real time. Virtual dual immersion accelerates acquisition, increases oral proficiency, motivates learners, and facilitates authentic intercultural exploration.</p>
    <ul class="pointslist">
      <li class="clear">
        <a href="#" data-largeimage="interaction_large.png"><img src="{{MEDIA_URL}}images/interaction_small.jpg"/></a>
        <div>We take care of finding tandem partners for your students. Our scheduling system makes it easy for students to reserve time with each other.</div>
      </li>
      <li class="clear">
        <a href="#" data-largeimage="interactionnotes_large.png"><img src="{{MEDIA_URL}}images/interactionnotes_small.jpg"/></a>
        <div>While typing to each other, Langolab provides tools to help with vocab and grammar, using artificial intelligence to link conversational content back to classroom lessons.</div>
      </li>
      <li class="clear">
        <a href="#" data-largeimage="dashboard_large.jpg"><img src="{{MEDIA_URL}}images/dashboard_small.jpg"/></a>
        <div>Our teacher dashboard makes it easy for teachers to grade students' interactions.</div>
      </li>
    </ul>
  </div>
  <div id="rightCol">
    
    
    <div id="rightPanel">
      <p>The Langolab Virtual Dual Immersion Platform is currently in development. We're actively seeking partner schools. Please contact us to learn more. 
        We can also be reached at <a class="ll-LinkButton" id="team_a"></a>.</p>
      <script type="text/javascript">
        document.getElementById('team_a').href = ["mailt", "o:team", "@lang", "olab.com"].join('');
        document.getElementById('team_a').innerHTML = ["team", "@lang", "olab.com"].join('');
      </script>
      <div id="ll_textBoxes">
        <form method="post" action="{% url marketing:interest %}" id="interest_form">
          {% csrf_token %}
          <ul class="errorlist" id="name_errors"></ul>
          <div class="input">
            <label for="id_name">Name</label>{{form.name}}
          </div>
          <div class="input">
            <label for="id_school">School</label>{{form.school}}
          </div>
          <div class="input">
            <label for="id_position">Position</label>{{form.position}}
          </div>
          <ul class="errorlist" id="email_errors"></ul>
          <div class="input">
            <label for="id_email">Email</label>{{form.email}}
          </div>
          <button>Submit</button>
        </form>
      </div>
      <p style="display:none">
        Thank you for your interest. We will contact you shortly.
      </p>
    </div>
    <h2>Think this is interesting? Share it!</h2>
    <div class="share">
      <script type="text/javascript" src="http://platform.linkedin.com/in.js"></script><script type="in/share" data-counter="right" data-url="http://www.langolab.com/"></script> 
    </div>
    <div class="share">
      <a href="http://twitter.com/share" class="twitter-share-button" data-count="horizontal" data-via="langolab">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
    </div>
    <div class="share">
      <script src="http://connect.facebook.net/en_US/all.js#xfbml=1"></script><fb:like href="http://www.langolab.com"></fb:like>
    </div>
  </div>
</div>
<div class="gwt-DecoratedPopupPanel hintDialog"><div class=""><table cellspacing="0" cellpadding="0" class=""><tbody><tr class="popupTop"><td class="popupTopLeft"><div class="popupTopLeftInner"></div></td><td class="popupTopCenter"><div class="popupTopCenterInner"></div></td><td class="popupTopRight"><div class="popupTopRightInner"></div></td></tr><tr class="popupMiddle"><td class="popupMiddleLeft"><div class="popupMiddleLeftInner"></div></td><td class="popupMiddleCenter"><div class="popupMiddleCenterInner popupContent">
  {% trans "Looking for the video site? Click here!" %}
  <div style="text-align: right;">
    <a href="#" class="ll-LinkButton">{% trans "close" %}</a>
  </div>
</div></td><td class="popupMiddleRight"><div class="popupMiddleRightInner"></div></td></tr><tr class="popupBottom"><td class="popupBottomLeft"><div class="popupBottomLeftInner"></div></td><td class="popupBottomCenter"><div class="popupBottomCenterInner"></div></td><td class="popupBottomRight"><div class="popupBottomRightInner"></div></td></tr></tbody></table></div></div>
{% endblock %}

django/web/templates/marketing/interaction-notes.html
{% extends "marketing/base.html" %}
{% block css %}
<link rel="stylesheet" media="screen" type="text/css" href="{{MEDIA_URL}}css/interaction.css"/>
{% endblock %}
{% block content %}
<div class="leftCol">
  <img src="{{MEDIA_URL}}images/sharon.png"/>
  <div>
    Anke, Germany 
  </div>
  <h3>Highest scores for today</h3>
  <ul class="top-score-list">
    <li class="top"><span class="scorer-name">Dieter</span> <span class="scorer-score">240</span></li>
    <li><span class="scorer-name">Melinda</span> <span class="scorer-score">235</span></li>
    <li><span class="scorer-name">John</span> <span class="scorer-score">160</span></li>
    <li><span class="scorer-name">Casey</span> <span class="scorer-score">158</span></li>
    <li><span class="scorer-name">Anke</span> <span class="scorer-score">140</span></li>
  </ul>
</div>
<div class="rightCol">
  <div style="height: 40px">
    <h2 style="padding-bottom: 8px;">Current Language: German</h2>
    <h2 style="padding-bottom: 8px;">Current Game: Negotiation</h2>
  </div>
  <div class="reminder">
    Remember, you are trying to get the price of the lot as far below $25,000 as possible!
  </div>
  <div class="scores">
    <div class="me"><span>You:</span> <span class="score">80</span></div>
    <div class="other"><span>Anke:</span> <span class="score">70</span></div>
  </div>
  <div class="conversation">
    <div class="utterance">
      <div class="name name-a">Anke</div>
      <div class="talk talk-a">Wie Sie schon wissen ziehen wir bald um, also können wir Ihnen das Grundstück verkaufen.  Wieviel möchten Sie dafür bezahlen?</div>
    </div>
    <div class="utterance">
      <div class="name name-b">Johanna</div>
      <div class="talk talk-b">Das habe ich mit meinem Mann überlegt, und wir können uns $15,000 leisten.</div>
    </div>
    <div class="utterance">
      <div class="name name-a">Anke</div>
      <div class="talk talk-a"><span class="highlighted">Naja, wir meinen, dass es etwas mehr Wert ist.</span>  Mindestens $30,000.  Wir haben schon echt viel Geld ausgeben, um es vor einigen Jahren in Ordnung zu bringen.</div>
    </div>
    <div class="utterance">
      <div class="name name-b">Johanna</div>
      <div class="talk talk-b">Ja sicher, aber Sie ziehen sowieso bald um, und ich bin die einzige Interessentin.  Reich sind wir nicht.  $20,000, sonst müssen Sie jemand anderes finden.</div>
    </div>
  </div>
  <input class="chat-input" type="text"></input>
</div>
<div class="gwt-DecoratedPopupPanel grammarDialog"><div class=""><table cellspacing="0" cellpadding="0" class=""><tbody><tr class="popupTop"><td class="popupTopLeft"><div class="popupTopLeftInner"></div></td><td class="popupTopCenter"><div class="popupTopCenterInner"></div></td><td class="popupTopRight"><div class="popupTopRightInner"></div></td></tr><tr class="popupMiddle"><td class="popupMiddleLeft"><div class="popupMiddleLeftInner"></div></td><td class="popupMiddleCenter"><div class="popupMiddleCenterInner popupContent">
  <h2>Naja, wir meinen, dass es etwas mehr Wert ist.</h2>
  <h2 class="translation">(Well, we think that it is a bit more value.)</h2>
  <h3 class="sectionTitle"><span class="title">The subordinating conjunction <em>dass</em>.</span> <span class="source">(From <a class="ll-LinkButton" href="#">Chapter 11</a>)</span></h3>
  <p>Clauses joined by subordinating conjunctions can follow these two word order patterns:</p>
  <ol class="conceptList">
    <li>
      The sentence begins with the main clause: In this case, the main clause has regular word order (meaning verb is second), and the dependent clause created by the conjunction has dependent word order (with verb last):
      <table class="concept">
        <tr>
          <th>Clause 1</th>
          <th>Conj.</th>
          <th>Clause 2</th>
        </tr>
        <tr>
          <td>Ich <span class="verb">muss</span> weit fahren<span class="comma">,</span></td>
          <td>weil</td>
          <td>die Polizei jagt mir <span class="verb">sind.</span></td>
        </tr>
      </table>
      <div class="example">(I must drive far because the police are chasing me.)</div>
    </li>
    <li>
      The sentence begins with the dependent clause: In this case the verb-second rule applies, moving the subject of the main clause after the verb:
      <table>
        <tr>
          <th>Clause 1</th>
          <th>Clause 2</th>
        </tr>
        <tr>
          <td>Weil die Polizei 
          <td>Ich <span class="verb">muss</span> weit fahren<span class="comma">,</span></td>
          <td>die Polizei jagt mir <span class="verb">sind.</span></td>
        </tr>
      </table>
    </li>
  </ol>
</div></td><td class="popupMiddleRight"><div class="popupMiddleRightInner"></div></td></tr><tr class="popupBottom"><td class="popupBottomLeft"><div class="popupBottomLeftInner"></div></td><td class="popupBottomCenter"><div class="popupBottomCenterInner"></div></td><td class="popupBottomRight"><div class="popupBottomRightInner"></div></td></tr></tbody></table></div></div>
{% endblock %}

django/web/templates/marketing/interaction.html
{% extends "marketing/base.html" %}
{% block css %}
<link rel="stylesheet" media="screen" type="text/css" href="{{MEDIA_URL}}css/interaction.css"/>
{% endblock %}
{% block content %}
<div class="leftCol">
  <img src="{{MEDIA_URL}}images/sharon.png"/>
  <div>
    Anke, Germany 
  </div>
  <h3>Highest scores for today</h3>
  <ul class="top-score-list">
    <li class="top"><span class="scorer-name">Dieter</span> <span class="scorer-score">240</span></li>
    <li><span class="scorer-name">Melinda</span> <span class="scorer-score">235</span></li>
    <li><span class="scorer-name">John</span> <span class="scorer-score">160</span></li>
    <li><span class="scorer-name">Casey</span> <span class="scorer-score">158</span></li>
    <li><span class="scorer-name">Anke</span> <span class="scorer-score">140</span></li>
  </ul>
</div>
<div class="rightCol">
  <div>
    <h2>Current Language: German</h2>
    <h2>Current Game: 20 Questions</h2>
  </div>
  <div class="scores">
    <div class="me"><span>You:</span> <span class="score">120</span></div>
    <div class="other"><span>Anke:</span> <span class="score">140</span></div>
  </div>
  <div class="timer timer-notmuchtime">
    <span class="time-left">Time left:</span> <span class="time">0:03</span>
  </div>
  <div class="conversation">
    <div class="utterance">
      <div class="name name-b">Johanna</div>
      <div class="talk talk-b">Ist es etwas, das man fahren kann?</div>
    </div>
    <div class="utterance">
      <div class="name name-a">Anke</div>
      <div class="talk talk-a">Ja.</div>
    </div>
    <div class="utterance">
      <div class="name name-b">Johanna</div>
      <div class="talk talk-b">Es ist ein Auto?</div>
    </div>
    <div class="utterance">
      <div class="name name-a">Anke</div>
      <div class="talk talk-a">Nein.</div>
    </div>
    <div class="utterance">
      <div class="name name-b">Johanna</div>
      <div class="talk talk-b">Brauchen es Benzin, um zu fahren?</div>
      <div class="talk talk-correction"><strong>Correction:</strong> Braucht es Benzin, um zu fahren?</div>
    </div>
    <div class="utterance">
      <div class="name name-a">Anke</div>
      <div class="talk talk-a">Nein.</div>
    </div>
    <div class="utterance">
      <div class="name name-b">Johanna</div>
      <div class="talk talk-b">Es ist ein Fahrrad?</div>
    </div>
    <div class="utterance">
      <div class="name name-a">Anke</div>
      <div class="talk talk-a">Ya, das ist korrect!</div>
    </div>
  </div>
  <input class="chat-input" type="text"></input>
</div>
{% endblock %}